language: elm
elm: 0.19.1

before_script:
  - elm-format src/ --yes
  - elm-format tests/ --yes

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm

notifications:
  email: false
